### ISSUE TITLE
Undefined or null value in Hash.entries

### ISSUE THREAD

**Issue by romfrolov** [damirka/redis-type#4]
**Error location:** https://github.com/damirka/redis-type/blob/master/lib/hash.js#L147

**Error message:**
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at /app/node_modules/redis-type/lib/hash.js:148:27
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**This is what getAll returns:**
```
null
```

**Expected output:**
```
{} // iterable
```

**Comment by damirka** [comment]
Gotcha. Gonna be updated soon.

**Comment by damirka** [comment]
@romfrolov There you go! Version 0.2.6 is published and ready to use.
